### ISSUE TITLE
Choosing projects without established account.

### ISSUE THREAD

**Issue by sebastianmbobrecki** [davidpanderson/science_united#6]
Selects Einstein@home as a project for given computer despite problem with account creation:
`

Web site | http://einstein.phys.uwm.edu/
-- | --
Science keywords | Astronomy, Detection and study of gravitational waves, Detection and study of pulsars
Location keywords | International, Albert Einstein Institute for Gravitational Physics
Account status | Transient error

``

Project | Score | Use cpu? | Use nvidia?
-- | -- | -- | --
Einstein@home | 0.1 | Yes | Yes

`

**Comment by davidpanderson** [comment]
Thanks for pointing this out.  The problem is that E@h recently stopped supporting account creation via RPC.  I'll try to resolve this issue with them.

**Comment by davidpanderson** [comment]
Another option - possibly preferable - is to use a single E@h account, rather than creating an account per SU user.

**Comment by sebastianmbobrecki** [comment]
> Another option - possibly preferable - is to use a single E@h account, rather than creating an account per SU user.

I Don't know if this is good idea as everybody will have single authenticator, and someone can use it to change options or to hijack account.

**Comment by davidpanderson** [comment]
It uses the weak authenticator

**Comment by sebastianmbobrecki** [comment]
If I take `<authenticator>` from account_XXX.xml and use it as "auth" cookie on given project website I can access all settings and change everything, including email and password.
![su_seti](https://user-images.githubusercontent.com/47056269/51897704-a2421700-23af-11e9-848d-6ea167bf95c0.png)

**Comment by davidpanderson** [comment]
The weak authenticator (which is used in this case) can't be used to log in to the web site:
https://boinc.berkeley.edu/wiki/Weak_account_key

**Comment by sebastianmbobrecki** [comment]
But it looks like in, for example, account_setiathome.berkeley.edu.xml (it's the same for other projects), in boinc dir, concted to SU and account created by SU, is normal authenticator, not weak. It don't contain "_" which I know is present in weak account keys of any project I participated for years. That's why I was able to access to what's on screenshot.

**Comment by sebastianmbobrecki** [comment]
I see that now for Einstein it actually uses weak account, but it has similar problem like with Amicable Numbers #5

**Comment by davidpanderson** [comment]
It was using the wrong weak authenticator.
I fixed this; if you reset E@h (in the manager) and synch with SU, E@h should go away.

**Comment by sebastianmbobrecki** [comment]
Now I see even stranger situation. Einstein totally disappeared from [How projects are chosen for...](https://scienceunited.org/su_hosts.php?action=project_select&host_id=2038), but it's still present on [Science projects page](https://scienceunited.org/su_user_projects.php).

P.S. In su_user_projects.php on line 74 "page_head()", should use "tra()".

**Comment by sebastianmbobrecki** [comment]
Returning to the main topic. A similar situation with the CPDN.
On https://scienceunited.org/su_user_projects.php I see:


NameClick for details | since | CPU hours | GPU hours | # successful jobs | # failed jobs | Account status | Allowed by prefs?
-- | -- | -- | -- | -- | -- | -- | --




Climateprediction.net | --- | 0.00 | 0.00 | 0 | 0 | --- | yes
-- | -- | -- | -- | -- | -- | -- | --


, so no account established. But on https://scienceunited.org/su_hosts.php?action=project_select&host_id=2038 there is:

Given the above info, this computer would do work for these projects: 

Project | Score | Use cpu? | Use nvidia?
-- | -- | -- | --
Climateprediction.net | 2 | Yes | No


So maybe in that case, it would be a good idea to switch all projects to use a single SU account and a weak account key.

**Comment by davidpanderson** [comment]
I've switched all projects to use a single account.  Let me know if any continuing problems.
